### ISSUE TITLE
Epic: Search engine

### ISSUE THREAD

**Issue by martinjonsson01** [martinjonsson01/contract-portal#58]
- [ ] Basic title search
- [ ] About us search
- [ ] Custom keyword search
- [ ] Web scraper indexer
